grant all privileges on database docker to docker;

create table items (
    id integer primary key not null generated by default as identity,
    name varchar(256) not null,
    quality integer not null,
    sellIn integer not null
);

insert into items (name, quality, sellIn)
values ('Aged Brie', 20, 10);

insert into items (name, quality, sellIn)
values ('Backstage passes to a TAFKAL80ETC concert', 20, 10);

insert into items (name, quality, sellIn)
values ('Sulfuras, Hand of Ragnaros', 20, 10);

insert into items (name, quality, sellIn)
values ('Normal', 20, 10);